<?php

namespace common\models;

use common\models\mongo\Products;
use Yii;

/**
 * This is the model class for table "abh_linesall".
 *
 * @property integer $id
 * @property integer $idlenens
 * @property integer $idsheerts
 * @property integer $idpillowcases
 * @property integer $duvetcover
 */
class Linesall extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'abh_linesall';
    }

    /*public function beforeSave($insert)
    {
        $product=Products::find()->where(['product_id'=>(int)$this->id_gods])->one();
        $add=$product->lines;
        foreach ($this as $key=>$val){
            if($key!='idlenens'&&$key!='id'&&isset($val))
                $add[$key]=$val;
        }
        $product->save();
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }*/

    public function getSheets(){
        return $this->hasOne(Gods::className(),['id'=>'idsheerts']);
    }

    public function getPillowcases(){
        return $this->hasOne(Gods::className(),['id'=>'idpillowcases']);
    }

    public function getDuvetscover(){
        return $this->hasOne(Gods::className(),['id'=>'duvetcover']);
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['idlenens'], 'required'],
            [['id', 'idlenens', 'idsheerts', 'idpillowcases', 'duvetcover'], 'integer'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'idlenens' => 'Idlenens',
            'idsheerts' => 'Idsheerts',
            'idpillowcases' => 'Idpillowcases',
            'duvetcover' => 'Duvetcover',
        ];
    }
}
